fix sqlalchemy.exc.ArgumentError from selecting counts in query.py
```
  File "/Users/bryan/llamanodes/web3-this-then-that-py/venv/lib/python3.10/site-packages/ape_cache/query.py", line 186, in _transaction_estimate_query_clause
    select([func.count()])
  File "/Users/bryan/llamanodes/web3-this-then-that-py/venv/lib/python3.10/site-packages/sqlalchemy/sql/_selectable_constructors.py", line 489, in select
    return Select(*entities)
  File "/Users/bryan/llamanodes/web3-this-then-that-py/venv/lib/python3.10/site-packages/sqlalchemy/sql/selectable.py", line 5130, in __init__
    self._raw_columns = [
  File "/Users/bryan/llamanodes/web3-this-then-that-py/venv/lib/python3.10/site-packages/sqlalchemy/sql/selectable.py", line 5131, in <listcomp>
    coercions.expect(
  File "/Users/bryan/llamanodes/web3-this-then-that-py/venv/lib/python3.10/site-packages/sqlalchemy/sql/coercions.py", line 413, in expect
    resolved = impl._literal_coercion(
  File "/Users/bryan/llamanodes/web3-this-then-that-py/venv/lib/python3.10/site-packages/sqlalchemy/sql/coercions.py", line 651, in _literal_coercion
    self._raise_for_expected(element, argname)
  File "/Users/bryan/llamanodes/web3-this-then-that-py/venv/lib/python3.10/site-packages/sqlalchemy/sql/coercions.py", line 1139, in _raise_for_expected
    return super()._raise_for_expected(
  File "/Users/bryan/llamanodes/web3-this-then-that-py/venv/lib/python3.10/site-packages/sqlalchemy/sql/coercions.py", line 710, in _raise_for_expected
    super()._raise_for_expected(
  File "/Users/bryan/llamanodes/web3-this-then-that-py/venv/lib/python3.10/site-packages/sqlalchemy/sql/coercions.py", line 535, in _raise_for_expected
    raise exc.ArgumentError(msg, code=code) from err
sqlalchemy.exc.ArgumentError: Column expression, FROM clause, or other columns clause element expected, got [<sqlalchemy.sql.functions.count at 0x1401aa530; count>]. Did you mean to say select(<sqlalchemy.sql.functions.count at 0x1401aa530; count>)?
```